package tests;

import org.openqa.selenium.WebDriver;
import org.testng.annotations.*;
import pages.LoginPage;
import utils.DriverFactory;
import config.TestConfig;

/**
 * BaseTest - Abstract base class for all test classes
 * Provides setup/teardown with automatic login/logout
 * 
 * This file is auto-generated by Xenon AI Test Automation Framework
 * Extend this class for tests that require Salesforce authentication
 */
public class BaseTest {
    
    protected WebDriver driver;
    protected LoginPage loginPage;
    
    /**
     * Setup before each test method
     * Creates WebDriver and performs login
     */
    @BeforeMethod
    public void setUp() {
        // Print configuration
        TestConfig.printConfig();
        
        // Create WebDriver instance
        driver = DriverFactory.createDriver(TestConfig.BROWSER, TestConfig.HEADLESS);
        
        // Create LoginPage instance
        loginPage = new LoginPage(driver);
        
        // Perform login
        loginPage.performLogin(
            TestConfig.LOGIN_URL,
            TestConfig.USERNAME,
            TestConfig.PASSWORD
        );
        
        // Handle any post-login modals
        loginPage.handlePostLoginModals();
    }
    
    /**
     * Teardown after each test method
     * Performs logout and quits WebDriver
     */
    @AfterMethod
    public void tearDown() {
        try {
            // Attempt logout
            if (loginPage != null && loginPage.isLoggedIn()) {
                loginPage.logout();
            }
        } catch (Exception e) {
            System.err.println("Logout failed in teardown: " + e.getMessage());
        } finally {
            // Always quit driver
            DriverFactory.quitDriver();
        }
    }
    
    /**
     * Get the authenticated WebDriver instance
     * @return WebDriver with active Salesforce session
     */
    protected WebDriver getAuthenticatedDriver() {
        return driver;
    }
}
