package locators;

import org.openqa.selenium.By;

/**
 * LoginLocators - Locators for Salesforce Login Page
 * 
 * This file is auto-generated by Xenon AI Test Automation Framework
 * Modify these locators as needed for your Salesforce instance
 */
public class LoginLocators {
    
    // Login Page Elements
    public static final By USERNAME_INPUT = By.cssSelector("#username");
    public static final By PASSWORD_INPUT = By.cssSelector("#password");
    public static final By LOGIN_BUTTON = By.cssSelector("#Login");
    public static final By REMEMBER_ME_CHECKBOX = By.cssSelector("#rememberUn");
    public static final By FORGOT_PASSWORD_LINK = By.cssSelector("#forgot_password_link");
    
    // Login Error Elements
    public static final By LOGIN_ERROR = By.cssSelector("#error");
    
    // Post-Login Elements (Home Page indicators)
    public static final By GLOBAL_HEADER = By.cssSelector(".slds-global-header");
    public static final By USER_PROFILE_BUTTON = By.cssSelector("button.slds-global-actions__avatar, .branding-userProfile-button");
    public static final By APP_LAUNCHER = By.cssSelector("button.slds-icon-waffle_container, div.slds-icon-waffle");
    public static final By APP_LAUNCHER_SEARCH = By.cssSelector("input[placeholder*='Search apps']");
    
    // Logout Elements
    public static final By LOGOUT_LINK = By.cssSelector("a[href*='logout'], a[href*='secur/logout.jsp']");
    public static final By USER_MENU_DROPDOWN = By.cssSelector(".slds-dropdown__list");
    
    // Navigation Elements
    public static final By TAB_BAR = By.cssSelector(".slds-tabs_default__nav");
    public static final By SEARCH_INPUT = By.cssSelector("input[name='search']");
    
    // Common Modal Elements
    public static final By MODAL_CONTAINER = By.cssSelector("section[role='dialog']");
    public static final By MODAL_CLOSE_BUTTON = By.cssSelector("button.slds-modal__close");
    public static final By MODAL_CONFIRM_BUTTON = By.cssSelector("button.slds-button--brand");
    
    // Toast Messages
    public static final By TOAST_MESSAGE = By.cssSelector("div.forceToastMessage, div.toastMessage");
    public static final By TOAST_CLOSE = By.cssSelector("button.toastClose");
    
    // Private constructor to prevent instantiation
    private LoginLocators() {}
}
