/**
 * LoginPage - Page Object for Salesforce Login/Logout functionality
 * Extends BasePage for common methods
 * 
 * This file is auto-generated by Xenon AI Test Automation Framework
 * Customize as needed for your Salesforce instance
 */

const BasePage = require('./BasePage');
const locators = require('../locators/LoginLocators');
const { click, fill, waitForElement, getText } = require('../utils/CommonActions');

class LoginPage extends BasePage {
  /**
   * @param {import('@playwright/test').Page} page - Playwright page object
   */
  constructor(page) {
    super(page);
  }

  /**
   * Navigate to the Salesforce login page
   * @param {string} loginUrl - The Salesforce login URL
   */
  async goToLoginPage(loginUrl) {
    await this.navigate(loginUrl);
    await waitForElement(this.page, locators.usernameInput);
  }

  /**
   * Perform login with provided credentials
   * @param {string} username - Salesforce username
   * @param {string} password - Salesforce password
   */
  async login(username, password) {
    // Wait for login page to load
    await waitForElement(this.page, locators.usernameInput);
    
    // Enter credentials
    await fill(this.page, locators.usernameInput, username);
    await fill(this.page, locators.passwordInput, password);
    
    // Click login button
    await click(this.page, locators.loginButton);
    
    // Wait for home page to load (global header indicates successful login)
    await this.waitForHomePage();
  }

  /**
   * Complete login flow - navigate to login page and login
   * @param {string} loginUrl - The Salesforce login URL
   * @param {string} username - Salesforce username
   * @param {string} password - Salesforce password
   */
  async performLogin(loginUrl, username, password) {
    await this.goToLoginPage(loginUrl);
    await this.login(username, password);
  }

  /**
   * Wait for home page to fully load after login
   */
  async waitForHomePage() {
    // Wait for global header to appear (indicates successful login)
    await waitForElement(this.page, locators.globalHeader, 60000);
    
    // Wait for any loading spinners to disappear
    await this.waitForSpinner();
    
    // Additional wait for page stability
    await this.page.waitForLoadState('networkidle');
  }

  /**
   * Perform logout from Salesforce
   */
  async logout() {
    try {
      // Click user profile button to open dropdown
      await click(this.page, locators.userProfileButton);
      
      // Wait for dropdown menu to appear
      await this.page.waitForTimeout(1000); // Small delay for animation
      
      // Click logout link
      await click(this.page, locators.logoutLink);
      
      // Wait for login page to reappear (confirms logout)
      await waitForElement(this.page, locators.usernameInput, 30000);
    } catch (error) {
      console.error('Logout failed, attempting direct logout URL:', error.message);
      // Fallback: Navigate directly to logout URL
      await this.page.goto('/secur/logout.jsp');
    }
  }

  /**
   * Check if user is logged in
   * @returns {Promise<boolean>}
   */
  async isLoggedIn() {
    return await this.isElementVisible(locators.globalHeader);
  }

  /**
   * Check if login error is displayed
   * @returns {Promise<boolean>}
   */
  async hasLoginError() {
    return await this.isElementVisible(locators.loginError);
  }

  /**
   * Get login error message
   * @returns {Promise<string>}
   */
  async getLoginErrorMessage() {
    if (await this.hasLoginError()) {
      return await getText(this.page, locators.loginError);
    }
    return '';
  }

  /**
   * Handle any welcome modals or popups after login
   */
  async dismissWelcomeModals() {
    try {
      const modalVisible = await this.isElementVisible(locators.modalContainer);
      if (modalVisible) {
        await click(this.page, locators.modalCloseButton);
        await this.page.waitForTimeout(500);
      }
    } catch {
      // No modals to dismiss, continue
    }
  }
}

module.exports = LoginPage;
