/**
 * Locators Index - Re-exports all locator modules
 * 
 * This file is auto-generated by Xenon AI Test Automation Framework
 * New locator files will be automatically added here
 */

const LoginLocators = require('./LoginLocators');

module.exports = {
  LoginLocators,
  // Additional locators will be added here as modules are generated
  // Example: AccountLocators: require('./AccountLocators'),
};
