/**
 * LoginLocators - Locators for Salesforce Login Page
 * 
 * This file is auto-generated by Xenon AI Test Automation Framework
 * Modify these locators as needed for your Salesforce instance
 */

module.exports = {
  // Login Page Elements
  usernameInput: '#username',
  passwordInput: '#password',
  loginButton: '#Login',
  rememberMeCheckbox: '#rememberUn',
  forgotPasswordLink: '#forgot_password_link',
  
  // Login Error Elements
  loginError: '#error',
  
  // Post-Login Elements (Home Page indicators)
  globalHeader: '.slds-global-header',
  userProfileButton: 'button.slds-global-actions__avatar, .branding-userProfile-button',
  appLauncher: 'button.slds-icon-waffle_container, div.slds-icon-waffle',
  
  // Logout Elements
  logoutLink: 'a[href*="logout"], a[href*="secur/logout.jsp"]',
  userMenuDropdown: '.slds-dropdown__list',
  
  // Navigation Elements
  tabBar: '.slds-tabs_default__nav',
  searchInput: 'input[name="search"]',
  
  // Common Modal Elements
  modalContainer: 'section[role="dialog"]',
  modalCloseButton: 'button.slds-modal__close',
  modalConfirmButton: 'button.slds-button--brand',
  
  // Toast Messages
  toastMessage: 'div.forceToastMessage, div.toastMessage',
  toastClose: 'button.toastClose',
};
