package utils;

import org.openqa.selenium.*;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.Select;
import org.openqa.selenium.support.ui.WebDriverWait;
import java.time.Duration;
import java.util.List;

/**
 * CommonActions - Reusable action methods for Selenium tests
 * Contains static utility methods for common web interactions
 * 
 * This file is auto-generated by Xenon AI Test Automation Framework
 * Add additional utility methods as needed for your project
 */
public class CommonActions {
    
    private static final int DEFAULT_TIMEOUT = 30;
    
    /**
     * Click on an element
     * @param driver - WebDriver instance
     * @param locator - By locator
     */
    public static void click(WebDriver driver, By locator) {
        WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(DEFAULT_TIMEOUT));
        wait.until(ExpectedConditions.elementToBeClickable(locator)).click();
    }
    
    /**
     * Fill text into an input field (clear first)
     * @param driver - WebDriver instance
     * @param locator - By locator
     * @param text - Text to enter
     */
    public static void fill(WebDriver driver, By locator, String text) {
        WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(DEFAULT_TIMEOUT));
        WebElement element = wait.until(ExpectedConditions.visibilityOfElementLocated(locator));
        element.clear();
        element.sendKeys(text);
    }
    
    /**
     * Get text from an element
     * @param driver - WebDriver instance
     * @param locator - By locator
     * @return String - Element text
     */
    public static String getText(WebDriver driver, By locator) {
        WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(DEFAULT_TIMEOUT));
        return wait.until(ExpectedConditions.visibilityOfElementLocated(locator)).getText();
    }
    
    /**
     * Wait for element to be visible
     * @param driver - WebDriver instance
     * @param locator - By locator
     * @return WebElement
     */
    public static WebElement waitForElement(WebDriver driver, By locator) {
        WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(DEFAULT_TIMEOUT));
        return wait.until(ExpectedConditions.visibilityOfElementLocated(locator));
    }
    
    /**
     * Wait for element to be visible with custom timeout
     * @param driver - WebDriver instance
     * @param locator - By locator
     * @param timeoutSeconds - Timeout in seconds
     * @return WebElement
     */
    public static WebElement waitForElement(WebDriver driver, By locator, int timeoutSeconds) {
        WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(timeoutSeconds));
        return wait.until(ExpectedConditions.visibilityOfElementLocated(locator));
    }
    
    /**
     * Wait for element to be clickable
     * @param driver - WebDriver instance
     * @param locator - By locator
     * @return WebElement
     */
    public static WebElement waitForClickable(WebDriver driver, By locator) {
        WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(DEFAULT_TIMEOUT));
        return wait.until(ExpectedConditions.elementToBeClickable(locator));
    }
    
    /**
     * Wait for element to disappear/hidden
     * @param driver - WebDriver instance
     * @param locator - By locator
     */
    public static void waitForElementHidden(WebDriver driver, By locator) {
        WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(DEFAULT_TIMEOUT));
        wait.until(ExpectedConditions.invisibilityOfElementLocated(locator));
    }
    
    /**
     * Select option from Salesforce Lightning combobox
     * @param driver - WebDriver instance
     * @param comboboxLocator - Locator for the combobox container
     * @param optionValue - The value to select
     */
    public static void selectComboboxOption(WebDriver driver, By comboboxLocator, String optionValue) {
        // Click the combobox to open dropdown
        click(driver, comboboxLocator);
        
        // Wait a moment for dropdown to open
        try { Thread.sleep(500); } catch (InterruptedException e) {}
        
        // Click the option by value
        By optionLocator = By.cssSelector("lightning-base-combobox-item[data-value='" + optionValue + "']");
        
        // If exact data-value doesn't work, try text contains
        try {
            click(driver, optionLocator);
        } catch (Exception e) {
            // Fallback: search by visible text
            By textOptionLocator = By.xpath("//lightning-base-combobox-item[contains(., '" + optionValue + "')]");
            click(driver, textOptionLocator);
        }
    }
    
    /**
     * Search and select from Salesforce Lightning lookup field
     * @param driver - WebDriver instance
     * @param lookupLocator - Locator for the lookup input
     * @param searchText - Text to search for
     */
    public static void searchAndSelectLookup(WebDriver driver, By lookupLocator, String searchText) {
        WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(DEFAULT_TIMEOUT));
        
        // Click and type in lookup field
        WebElement lookupInput = wait.until(ExpectedConditions.elementToBeClickable(lookupLocator));
        lookupInput.click();
        lookupInput.sendKeys(searchText);
        
        // Wait for results and select
        try { Thread.sleep(1000); } catch (InterruptedException e) {}
        
        By resultLocator = By.xpath("//lightning-base-combobox-item[contains(., '" + searchText + "')]");
        click(driver, resultLocator);
    }
    
    /**
     * Select from standard HTML dropdown
     * @param driver - WebDriver instance
     * @param locator - By locator
     * @param visibleText - Visible text of option
     */
    public static void selectDropdownByText(WebDriver driver, By locator, String visibleText) {
        WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(DEFAULT_TIMEOUT));
        WebElement element = wait.until(ExpectedConditions.visibilityOfElementLocated(locator));
        Select select = new Select(element);
        select.selectByVisibleText(visibleText);
    }
    
    /**
     * Select from standard HTML dropdown by value
     * @param driver - WebDriver instance
     * @param locator - By locator
     * @param value - Value attribute of option
     */
    public static void selectDropdownByValue(WebDriver driver, By locator, String value) {
        WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(DEFAULT_TIMEOUT));
        WebElement element = wait.until(ExpectedConditions.visibilityOfElementLocated(locator));
        Select select = new Select(element);
        select.selectByValue(value);
    }
    
    /**
     * Check if element is visible
     * @param driver - WebDriver instance
     * @param locator - By locator
     * @return boolean
     */
    public static boolean isElementVisible(WebDriver driver, By locator) {
        try {
            return driver.findElement(locator).isDisplayed();
        } catch (NoSuchElementException | StaleElementReferenceException e) {
            return false;
        }
    }
    
    /**
     * Check if element exists
     * @param driver - WebDriver instance
     * @param locator - By locator
     * @return boolean
     */
    public static boolean isElementPresent(WebDriver driver, By locator) {
        try {
            driver.findElement(locator);
            return true;
        } catch (NoSuchElementException e) {
            return false;
        }
    }
    
    /**
     * Get attribute value from element
     * @param driver - WebDriver instance
     * @param locator - By locator
     * @param attribute - Attribute name
     * @return String - Attribute value
     */
    public static String getAttribute(WebDriver driver, By locator, String attribute) {
        WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(DEFAULT_TIMEOUT));
        return wait.until(ExpectedConditions.visibilityOfElementLocated(locator)).getAttribute(attribute);
    }
    
    /**
     * JavaScript click (useful when element is obscured)
     * @param driver - WebDriver instance
     * @param locator - By locator
     */
    public static void jsClick(WebDriver driver, By locator) {
        WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(DEFAULT_TIMEOUT));
        WebElement element = wait.until(ExpectedConditions.presenceOfElementLocated(locator));
        ((JavascriptExecutor) driver).executeScript("arguments[0].click();", element);
    }
    
    /**
     * Scroll element into view
     * @param driver - WebDriver instance
     * @param locator - By locator
     */
    public static void scrollIntoView(WebDriver driver, By locator) {
        WebElement element = driver.findElement(locator);
        ((JavascriptExecutor) driver).executeScript(
            "arguments[0].scrollIntoView({behavior: 'smooth', block: 'center'});", 
            element
        );
    }
    
    /**
     * Wait for Salesforce Lightning spinner to disappear
     * @param driver - WebDriver instance
     */
    public static void waitForSpinner(WebDriver driver) {
        try {
            Thread.sleep(500);
            WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(DEFAULT_TIMEOUT));
            wait.until(ExpectedConditions.invisibilityOfElementLocated(
                By.cssSelector("lightning-spinner, .slds-spinner_container")
            ));
        } catch (Exception e) {
            // Spinner may not appear
        }
    }
    
    /**
     * Get all elements matching locator
     * @param driver - WebDriver instance
     * @param locator - By locator
     * @return List of WebElements
     */
    public static List<WebElement> getElements(WebDriver driver, By locator) {
        WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(DEFAULT_TIMEOUT));
        wait.until(ExpectedConditions.presenceOfElementLocated(locator));
        return driver.findElements(locator);
    }
    
    /**
     * Switch to window by index
     * @param driver - WebDriver instance
     * @param windowIndex - Window index (0-based)
     */
    public static void switchToWindow(WebDriver driver, int windowIndex) {
        Object[] windowHandles = driver.getWindowHandles().toArray();
        if (windowIndex < windowHandles.length) {
            driver.switchTo().window((String) windowHandles[windowIndex]);
        }
    }
    
    /**
     * Get toast message text from Salesforce
     * @param driver - WebDriver instance
     * @return String - Toast message text
     */
    public static String getToastMessage(WebDriver driver) {
        By toastLocator = By.cssSelector("div.forceToastMessage span.toastMessage, div.toastMessage");
        return getText(driver, toastLocator);
    }
    
    /**
     * Wait for toast message to appear
     * @param driver - WebDriver instance
     * @return WebElement - Toast element
     */
    public static WebElement waitForToast(WebDriver driver) {
        By toastLocator = By.cssSelector("div.forceToastMessage, div.toastContainer");
        return waitForElement(driver, toastLocator);
    }
}
