package utils;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.firefox.FirefoxOptions;
import org.openqa.selenium.edge.EdgeDriver;
import org.openqa.selenium.edge.EdgeOptions;
import io.github.bonigarcia.wdm.WebDriverManager;

/**
 * DriverFactory - WebDriver creation and configuration
 * Supports Chrome, Firefox, and Edge browsers
 * 
 * This file is auto-generated by Xenon AI Test Automation Framework
 * Customize browser options as needed for your project
 */
public class DriverFactory {
    
    private static ThreadLocal<WebDriver> driver = new ThreadLocal<>();
    
    /**
     * Get or create WebDriver instance for current thread
     * @return WebDriver instance
     */
    public static WebDriver getDriver() {
        if (driver.get() == null) {
            driver.set(createDriver("chrome", false));
        }
        return driver.get();
    }
    
    /**
     * Create WebDriver with specified browser
     * @param browser - Browser name (chrome, firefox, edge)
     * @param headless - Run in headless mode
     * @return WebDriver instance
     */
    public static WebDriver createDriver(String browser, boolean headless) {
        WebDriver webDriver;
        
        switch (browser.toLowerCase()) {
            case "firefox":
                webDriver = createFirefoxDriver(headless);
                break;
            case "edge":
                webDriver = createEdgeDriver(headless);
                break;
            case "chrome":
            default:
                webDriver = createChromeDriver(headless);
                break;
        }
        
        // Configure browser window
        webDriver.manage().window().maximize();
        
        driver.set(webDriver);
        return webDriver;
    }
    
    /**
     * Create Chrome WebDriver
     * @param headless - Run in headless mode
     * @return ChromeDriver instance
     */
    private static WebDriver createChromeDriver(boolean headless) {
        WebDriverManager.chromedriver().setup();
        
        ChromeOptions options = new ChromeOptions();
        
        // Common options for stability
        options.addArguments("--disable-blink-features=AutomationControlled");
        options.addArguments("--disable-notifications");
        options.addArguments("--disable-popup-blocking");
        options.addArguments("--disable-infobars");
        options.addArguments("--no-sandbox");
        options.addArguments("--disable-dev-shm-usage");
        options.addArguments("--remote-allow-origins=*");
        
        if (headless) {
            options.addArguments("--headless=new");
            options.addArguments("--window-size=1920,1080");
        }
        
        // Exclude automation switches to avoid detection
        options.setExperimentalOption("excludeSwitches", new String[]{"enable-automation"});
        
        return new ChromeDriver(options);
    }
    
    /**
     * Create Firefox WebDriver
     * @param headless - Run in headless mode
     * @return FirefoxDriver instance
     */
    private static WebDriver createFirefoxDriver(boolean headless) {
        WebDriverManager.firefoxdriver().setup();
        
        FirefoxOptions options = new FirefoxOptions();
        
        if (headless) {
            options.addArguments("-headless");
        }
        
        options.addPreference("dom.webnotifications.enabled", false);
        options.addPreference("dom.push.enabled", false);
        
        return new FirefoxDriver(options);
    }
    
    /**
     * Create Edge WebDriver
     * @param headless - Run in headless mode
     * @return EdgeDriver instance
     */
    private static WebDriver createEdgeDriver(boolean headless) {
        WebDriverManager.edgedriver().setup();
        
        EdgeOptions options = new EdgeOptions();
        
        options.addArguments("--disable-notifications");
        options.addArguments("--no-sandbox");
        
        if (headless) {
            options.addArguments("--headless=new");
            options.addArguments("--window-size=1920,1080");
        }
        
        return new EdgeDriver(options);
    }
    
    /**
     * Quit WebDriver and clean up thread local
     */
    public static void quitDriver() {
        WebDriver currentDriver = driver.get();
        if (currentDriver != null) {
            currentDriver.quit();
            driver.remove();
        }
    }
    
    /**
     * Get browser name from environment variable or default to chrome
     * @return Browser name
     */
    public static String getBrowserFromEnv() {
        String browser = System.getenv("BROWSER");
        if (browser == null || browser.isEmpty()) {
            browser = System.getProperty("browser", "chrome");
        }
        return browser;
    }
    
    /**
     * Check if headless mode is enabled via environment
     * @return boolean
     */
    public static boolean isHeadlessFromEnv() {
        String headless = System.getenv("HEADLESS");
        if (headless == null) {
            headless = System.getProperty("headless", "false");
        }
        return Boolean.parseBoolean(headless);
    }
}
