/**
 * CommonActions - Reusable browser actions for Playwright tests
 * 
 * This file is auto-generated by Xenon AI Test Automation Framework
 * Contains common methods used across all page objects
 */

/**
 * Click on an element with wait
 * @param {import('@playwright/test').Page} page - Playwright page object
 * @param {string} selector - Element selector
 * @param {number} timeout - Optional timeout in milliseconds
 */
async function click(page, selector, timeout = 30000) {
  await page.waitForSelector(selector, { state: 'visible', timeout });
  await page.click(selector);
}

/**
 * Double click on an element
 * @param {import('@playwright/test').Page} page - Playwright page object
 * @param {string} selector - Element selector
 * @param {number} timeout - Optional timeout in milliseconds
 */
async function doubleClick(page, selector, timeout = 30000) {
  await page.waitForSelector(selector, { state: 'visible', timeout });
  await page.dblclick(selector);
}

/**
 * Fill an input field with text
 * @param {import('@playwright/test').Page} page - Playwright page object
 * @param {string} selector - Element selector
 * @param {string} text - Text to fill
 * @param {number} timeout - Optional timeout in milliseconds
 */
async function fill(page, selector, text, timeout = 30000) {
  await page.waitForSelector(selector, { state: 'visible', timeout });
  await page.fill(selector, text);
}

/**
 * Clear and fill an input field
 * @param {import('@playwright/test').Page} page - Playwright page object
 * @param {string} selector - Element selector
 * @param {string} text - Text to fill
 * @param {number} timeout - Optional timeout in milliseconds
 */
async function clearAndFill(page, selector, text, timeout = 30000) {
  await page.waitForSelector(selector, { state: 'visible', timeout });
  await page.fill(selector, ''); // Clear first
  await page.fill(selector, text);
}

/**
 * Type text into an input field (character by character)
 * @param {import('@playwright/test').Page} page - Playwright page object
 * @param {string} selector - Element selector
 * @param {string} text - Text to type
 * @param {number} delay - Delay between keystrokes in milliseconds
 */
async function type(page, selector, text, delay = 100) {
  await page.waitForSelector(selector, { state: 'visible' });
  await page.type(selector, text, { delay });
}

/**
 * Wait for an element to be visible
 * @param {import('@playwright/test').Page} page - Playwright page object
 * @param {string} selector - Element selector
 * @param {number} timeout - Optional timeout in milliseconds
 */
async function waitForElement(page, selector, timeout = 30000) {
  await page.waitForSelector(selector, { state: 'visible', timeout });
}

/**
 * Wait for an element to be hidden
 * @param {import('@playwright/test').Page} page - Playwright page object
 * @param {string} selector - Element selector
 * @param {number} timeout - Optional timeout in milliseconds
 */
async function waitForElementHidden(page, selector, timeout = 30000) {
  await page.waitForSelector(selector, { state: 'hidden', timeout });
}

/**
 * Get text content of an element
 * @param {import('@playwright/test').Page} page - Playwright page object
 * @param {string} selector - Element selector
 * @returns {Promise<string>}
 */
async function getText(page, selector) {
  await page.waitForSelector(selector, { state: 'visible' });
  return await page.textContent(selector);
}

/**
 * Get all text contents of elements matching selector
 * @param {import('@playwright/test').Page} page - Playwright page object
 * @param {string} selector - Element selector
 * @returns {Promise<string[]>}
 */
async function getAllTexts(page, selector) {
  await page.waitForSelector(selector);
  return await page.locator(selector).allTextContents();
}

/**
 * Get attribute value of an element
 * @param {import('@playwright/test').Page} page - Playwright page object
 * @param {string} selector - Element selector
 * @param {string} attribute - Attribute name
 * @returns {Promise<string|null>}
 */
async function getAttribute(page, selector, attribute) {
  await page.waitForSelector(selector, { state: 'visible' });
  return await page.getAttribute(selector, attribute);
}

/**
 * Check if an element is visible
 * @param {import('@playwright/test').Page} page - Playwright page object
 * @param {string} selector - Element selector
 * @returns {Promise<boolean>}
 */
async function isVisible(page, selector) {
  try {
    await page.waitForSelector(selector, { state: 'visible', timeout: 5000 });
    return true;
  } catch {
    return false;
  }
}

/**
 * Check if a checkbox is checked
 * @param {import('@playwright/test').Page} page - Playwright page object
 * @param {string} selector - Element selector
 * @returns {Promise<boolean>}
 */
async function isChecked(page, selector) {
  return await page.isChecked(selector);
}

/**
 * Check a checkbox if not already checked
 * @param {import('@playwright/test').Page} page - Playwright page object
 * @param {string} selector - Element selector
 */
async function check(page, selector) {
  const checked = await page.isChecked(selector);
  if (!checked) {
    await page.check(selector);
  }
}

/**
 * Uncheck a checkbox if checked
 * @param {import('@playwright/test').Page} page - Playwright page object
 * @param {string} selector - Element selector
 */
async function uncheck(page, selector) {
  const checked = await page.isChecked(selector);
  if (checked) {
    await page.uncheck(selector);
  }
}

/**
 * Select option from dropdown by value
 * @param {import('@playwright/test').Page} page - Playwright page object
 * @param {string} selector - Element selector
 * @param {string} value - Option value
 */
async function selectByValue(page, selector, value) {
  await page.waitForSelector(selector, { state: 'visible' });
  await page.selectOption(selector, { value });
}

/**
 * Select option from dropdown by label
 * @param {import('@playwright/test').Page} page - Playwright page object
 * @param {string} selector - Element selector
 * @param {string} label - Option label
 */
async function selectByLabel(page, selector, label) {
  await page.waitForSelector(selector, { state: 'visible' });
  await page.selectOption(selector, { label });
}

/**
 * Select option from Salesforce Lightning combobox/picklist
 * @param {import('@playwright/test').Page} page - Playwright page object
 * @param {string} comboboxSelector - Combobox selector
 * @param {string} optionText - Option text to select
 */
async function selectComboboxOption(page, comboboxSelector, optionText) {
  // Click combobox to open dropdown
  await click(page, `${comboboxSelector} button`);
  
  // Wait for dropdown options to appear
  await page.waitForSelector('lightning-base-combobox-item', { state: 'visible' });
  
  // Click the option
  await page.click(`lightning-base-combobox-item:has-text("${optionText}")`);
}

/**
 * Search and select from Salesforce Lightning lookup field
 * @param {import('@playwright/test').Page} page - Playwright page object
 * @param {string} lookupSelector - Lookup field selector
 * @param {string} searchText - Text to search for
 */
async function searchAndSelectLookup(page, lookupSelector, searchText) {
  // Click lookup field to focus
  await click(page, `${lookupSelector} input`);
  
  // Type search text
  await fill(page, `${lookupSelector} input`, searchText);
  
  // Wait for search results
  await page.waitForSelector('lightning-base-combobox-item', { state: 'visible' });
  
  // Click first result
  await page.click('lightning-base-combobox-item:first-child');
}

/**
 * Hover over an element
 * @param {import('@playwright/test').Page} page - Playwright page object
 * @param {string} selector - Element selector
 */
async function hover(page, selector) {
  await page.waitForSelector(selector, { state: 'visible' });
  await page.hover(selector);
}

/**
 * Scroll element into view
 * @param {import('@playwright/test').Page} page - Playwright page object
 * @param {string} selector - Element selector
 */
async function scrollIntoView(page, selector) {
  await page.locator(selector).scrollIntoViewIfNeeded();
}

/**
 * Press a key on the keyboard
 * @param {import('@playwright/test').Page} page - Playwright page object
 * @param {string} key - Key to press (e.g., 'Enter', 'Escape', 'Tab')
 */
async function pressKey(page, key) {
  await page.keyboard.press(key);
}

/**
 * Take a screenshot
 * @param {import('@playwright/test').Page} page - Playwright page object
 * @param {string} name - Screenshot name
 */
async function takeScreenshot(page, name) {
  await page.screenshot({ path: `screenshots/${name}.png`, fullPage: true });
}

/**
 * Wait for Salesforce spinner/loader to disappear
 * @param {import('@playwright/test').Page} page - Playwright page object
 */
async function waitForSpinner(page) {
  try {
    await page.waitForSelector('lightning-spinner', { state: 'hidden', timeout: 10000 });
  } catch {
    // Spinner may not be present, continue
  }
}

/**
 * Wait for toast message and return its text
 * @param {import('@playwright/test').Page} page - Playwright page object
 * @returns {Promise<string>}
 */
async function getToastMessage(page) {
  await page.waitForSelector('div.forceToastMessage, div.toastMessage', { 
    state: 'visible', 
    timeout: 10000 
  });
  return await getText(page, 'div.forceToastMessage, div.toastMessage');
}

/**
 * Wait for specific time
 * @param {number} ms - Milliseconds to wait
 */
async function wait(ms) {
  return new Promise(resolve => setTimeout(resolve, ms));
}

module.exports = {
  click,
  doubleClick,
  fill,
  clearAndFill,
  type,
  waitForElement,
  waitForElementHidden,
  getText,
  getAllTexts,
  getAttribute,
  isVisible,
  isChecked,
  check,
  uncheck,
  selectByValue,
  selectByLabel,
  selectComboboxOption,
  searchAndSelectLookup,
  hover,
  scrollIntoView,
  pressKey,
  takeScreenshot,
  waitForSpinner,
  getToastMessage,
  wait,
};
