/**
 * Test Data Utilities
 * Helper functions for generating test data
 * 
 * This file is auto-generated by Xenon AI Test Automation Framework
 */

/**
 * Generate a random string
 * @param {number} length - Length of string
 * @returns {string}
 */
function randomString(length = 10) {
  const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
  let result = '';
  for (let i = 0; i < length; i++) {
    result += chars.charAt(Math.floor(Math.random() * chars.length));
  }
  return result;
}

/**
 * Generate a unique timestamp-based identifier
 * @returns {string}
 */
function uniqueId() {
  return `TEST_${Date.now()}_${Math.floor(Math.random() * 1000)}`;
}

/**
 * Generate a random email
 * @param {string} domain - Email domain (default: example.com)
 * @returns {string}
 */
function randomEmail(domain = 'example.com') {
  return `test.${randomString(8)}@${domain}`;
}

/**
 * Generate a random phone number
 * @returns {string}
 */
function randomPhone() {
  return `+1${Math.floor(Math.random() * 9000000000) + 1000000000}`;
}

/**
 * Get current date in YYYY-MM-DD format
 * @returns {string}
 */
function currentDate() {
  return new Date().toISOString().split('T')[0];
}

/**
 * Get future date
 * @param {number} days - Number of days in future
 * @returns {string}
 */
function futureDate(days = 30) {
  const date = new Date();
  date.setDate(date.getDate() + days);
  return date.toISOString().split('T')[0];
}

module.exports = {
  randomString,
  uniqueId,
  randomEmail,
  randomPhone,
  currentDate,
  futureDate,
};
