/**
 * Authentication Fixture - Provides authenticated Playwright page
 * 
 * This fixture automatically handles login before each test
 * and logout after each test
 * 
 * This file is auto-generated by Xenon AI Test Automation Framework
 */

const playwrightTest = require('@playwright/test');
const base = playwrightTest.test;
const LoginPage = require('../pages/LoginPage');

// Extend base test with authentication fixture
const test = base.extend({
  /**
   * Provides an authenticated page object
   * Login is performed before the test, logout after
   */
  authenticatedPage: async ({ page }, use) => {
    // Get credentials from environment variables
    const loginUrl = process.env.SALESFORCE_LOGIN_URL || 'https://login.salesforce.com';
    const username = process.env.SALESFORCE_USERNAME || '';
    const password = process.env.SALESFORCE_PASSWORD || '';

    if (!username || !password) {
      throw new Error('SALESFORCE_USERNAME and SALESFORCE_PASSWORD must be set in environment variables');
    }

    // Perform login
    const loginPage = new LoginPage(page);
    await loginPage.performLogin(loginUrl, username, password);
    
    // Dismiss any welcome modals
    await loginPage.dismissWelcomeModals();

    // Provide the authenticated page to the test
    await use(page);

    // Cleanup: Logout after test
    try {
      await loginPage.logout();
    } catch (error) {
      console.log('Logout failed (test may have already logged out):', error.message);
    }
  },
});

module.exports = { test };
