/**
 * BasePage - Abstract base class for all Page Objects
 * Contains common methods used across all pages
 * 
 * This file is auto-generated by Xenon AI Test Automation Framework
 * Customize as needed for your project
 */

class BasePage {
  /**
   * @param {import('@playwright/test').Page} page - Playwright page object
   */
  constructor(page) {
    this.page = page;
    this.timeout = 30000; // Default timeout for operations
  }

  /**
   * Navigate to a specific URL
   * @param {string} url - The URL to navigate to
   */
  async navigate(url) {
    await this.page.goto(url, { waitUntil: 'networkidle' });
  }

  /**
   * Wait for page to be fully loaded
   */
  async waitForPageLoad() {
    await this.page.waitForLoadState('networkidle');
  }

  /**
   * Get the current page title
   * @returns {Promise<string>}
   */
  async getPageTitle() {
    return await this.page.title();
  }

  /**
   * Get the current page URL
   * @returns {Promise<string>}
   */
  async getCurrentUrl() {
    return this.page.url();
  }

  /**
   * Take a screenshot of the current page
   * @param {string} name - Screenshot name
   */
  async takeScreenshot(name) {
    await this.page.screenshot({ path: `screenshots/${name}.png`, fullPage: true });
  }

  /**
   * Wait for an element to be visible
   * @param {string} selector - Element selector
   * @param {number} timeout - Optional timeout in milliseconds
   */
  async waitForElement(selector, timeout = this.timeout) {
    await this.page.waitForSelector(selector, { state: 'visible', timeout });
  }

  /**
   * Wait for an element to be hidden
   * @param {string} selector - Element selector
   * @param {number} timeout - Optional timeout in milliseconds
   */
  async waitForElementHidden(selector, timeout = this.timeout) {
    await this.page.waitForSelector(selector, { state: 'hidden', timeout });
  }

  /**
   * Check if an element exists on the page
   * @param {string} selector - Element selector
   * @returns {Promise<boolean>}
   */
  async isElementVisible(selector) {
    try {
      await this.page.waitForSelector(selector, { state: 'visible', timeout: 5000 });
      return true;
    } catch {
      return false;
    }
  }

  /**
   * Get text content of an element
   * @param {string} selector - Element selector
   * @returns {Promise<string>}
   */
  async getText(selector) {
    await this.waitForElement(selector);
    return await this.page.textContent(selector);
  }

  /**
   * Get attribute value of an element
   * @param {string} selector - Element selector
   * @param {string} attribute - Attribute name
   * @returns {Promise<string|null>}
   */
  async getAttribute(selector, attribute) {
    await this.waitForElement(selector);
    return await this.page.getAttribute(selector, attribute);
  }

  /**
   * Scroll element into view
   * @param {string} selector - Element selector
   */
  async scrollIntoView(selector) {
    await this.page.locator(selector).scrollIntoViewIfNeeded();
  }

  /**
   * Wait for spinner/loader to disappear (Salesforce specific)
   */
  async waitForSpinner() {
    try {
      await this.page.waitForSelector('lightning-spinner', { state: 'hidden', timeout: 10000 });
    } catch {
      // Spinner may not be present, continue
    }
  }

  /**
   * Handle any modal dialogs that appear
   * @param {string} action - 'accept' or 'dismiss'
   */
  async handleDialog(action = 'accept') {
    this.page.on('dialog', async (dialog) => {
      if (action === 'accept') {
        await dialog.accept();
      } else {
        await dialog.dismiss();
      }
    });
  }
}

module.exports = BasePage;
