package pages;

import org.openqa.selenium.*;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.support.PageFactory;
import java.time.Duration;
import java.io.File;
import java.nio.file.Files;
import java.nio.file.Paths;

/**
 * BasePage - Abstract base class for all Page Objects
 * Contains common methods used across all pages
 * 
 * This file is auto-generated by Xenon AI Test Automation Framework
 * Customize as needed for your project
 */
public class BasePage {
    
    protected WebDriver driver;
    protected WebDriverWait wait;
    protected static final int DEFAULT_TIMEOUT = 30;
    
    /**
     * Constructor - Initialize WebDriver and WebDriverWait
     * @param driver - WebDriver instance
     */
    public BasePage(WebDriver driver) {
        this.driver = driver;
        this.wait = new WebDriverWait(driver, Duration.ofSeconds(DEFAULT_TIMEOUT));
        PageFactory.initElements(driver, this);
    }
    
    /**
     * Navigate to a specific URL
     * @param url - The URL to navigate to
     */
    public void navigate(String url) {
        driver.get(url);
        waitForPageLoad();
    }
    
    /**
     * Wait for page to be fully loaded using document ready state
     */
    public void waitForPageLoad() {
        wait.until(webDriver -> 
            ((JavascriptExecutor) webDriver)
                .executeScript("return document.readyState")
                .equals("complete"));
    }
    
    /**
     * Get the current page title
     * @return String - Page title
     */
    public String getPageTitle() {
        return driver.getTitle();
    }
    
    /**
     * Get the current page URL
     * @return String - Current URL
     */
    public String getCurrentUrl() {
        return driver.getCurrentUrl();
    }
    
    /**
     * Take a screenshot of the current page
     * @param name - Screenshot name
     */
    public void takeScreenshot(String name) {
        try {
            File screenshotDir = new File("screenshots");
            if (!screenshotDir.exists()) {
                screenshotDir.mkdirs();
            }
            File screenshot = ((TakesScreenshot) driver).getScreenshotAs(OutputType.FILE);
            Files.copy(screenshot.toPath(), Paths.get("screenshots/" + name + ".png"));
        } catch (Exception e) {
            System.err.println("Failed to take screenshot: " + e.getMessage());
        }
    }
    
    /**
     * Wait for an element to be visible
     * @param locator - By locator
     * @return WebElement
     */
    public WebElement waitForElement(By locator) {
        return wait.until(ExpectedConditions.visibilityOfElementLocated(locator));
    }
    
    /**
     * Wait for an element to be visible with custom timeout
     * @param locator - By locator
     * @param timeoutSeconds - Timeout in seconds
     * @return WebElement
     */
    public WebElement waitForElement(By locator, int timeoutSeconds) {
        WebDriverWait customWait = new WebDriverWait(driver, Duration.ofSeconds(timeoutSeconds));
        return customWait.until(ExpectedConditions.visibilityOfElementLocated(locator));
    }
    
    /**
     * Wait for an element to be clickable
     * @param locator - By locator
     * @return WebElement
     */
    public WebElement waitForClickable(By locator) {
        return wait.until(ExpectedConditions.elementToBeClickable(locator));
    }
    
    /**
     * Wait for an element to be hidden/invisible
     * @param locator - By locator
     */
    public void waitForElementHidden(By locator) {
        wait.until(ExpectedConditions.invisibilityOfElementLocated(locator));
    }
    
    /**
     * Check if an element is visible on the page
     * @param locator - By locator
     * @return boolean
     */
    public boolean isElementVisible(By locator) {
        try {
            return driver.findElement(locator).isDisplayed();
        } catch (NoSuchElementException | StaleElementReferenceException e) {
            return false;
        }
    }
    
    /**
     * Check if an element exists on the page
     * @param locator - By locator
     * @return boolean
     */
    public boolean isElementPresent(By locator) {
        try {
            driver.findElement(locator);
            return true;
        } catch (NoSuchElementException e) {
            return false;
        }
    }
    
    /**
     * Click on an element with explicit wait
     * @param locator - By locator
     */
    public void click(By locator) {
        waitForClickable(locator).click();
    }
    
    /**
     * Clear and type text into an input field
     * @param locator - By locator
     * @param text - Text to type
     */
    public void fill(By locator, String text) {
        WebElement element = waitForElement(locator);
        element.clear();
        element.sendKeys(text);
    }
    
    /**
     * Get text from an element
     * @param locator - By locator
     * @return String - Element text
     */
    public String getText(By locator) {
        return waitForElement(locator).getText();
    }
    
    /**
     * Wait for Salesforce Lightning spinner to disappear
     */
    public void waitForSpinner() {
        try {
            Thread.sleep(500); // Small delay to let spinner appear
            wait.until(ExpectedConditions.invisibilityOfElementLocated(
                By.cssSelector("lightning-spinner, .slds-spinner_container")
            ));
        } catch (Exception e) {
            // Spinner may not appear, continue
        }
    }
    
    /**
     * Scroll element into view
     * @param locator - By locator
     */
    public void scrollIntoView(By locator) {
        WebElement element = driver.findElement(locator);
        ((JavascriptExecutor) driver).executeScript(
            "arguments[0].scrollIntoView({behavior: 'smooth', block: 'center'});", 
            element
        );
    }
    
    /**
     * JavaScript click (useful when normal click is intercepted)
     * @param locator - By locator
     */
    public void jsClick(By locator) {
        WebElement element = waitForElement(locator);
        ((JavascriptExecutor) driver).executeScript("arguments[0].click();", element);
    }
    
    /**
     * Wait for specific text to be present in element
     * @param locator - By locator
     * @param text - Text to wait for
     */
    public void waitForText(By locator, String text) {
        wait.until(ExpectedConditions.textToBePresentInElementLocated(locator, text));
    }
    
    /**
     * Accept browser alert if present
     */
    public void acceptAlert() {
        try {
            wait.until(ExpectedConditions.alertIsPresent());
            driver.switchTo().alert().accept();
        } catch (Exception e) {
            // No alert present
        }
    }
    
    /**
     * Switch to iframe by locator
     * @param frameLocator - By locator for iframe
     */
    public void switchToFrame(By frameLocator) {
        wait.until(ExpectedConditions.frameToBeAvailableAndSwitchToIt(frameLocator));
    }
    
    /**
     * Switch back to main/default content
     */
    public void switchToDefaultContent() {
        driver.switchTo().defaultContent();
    }
}
