package pages;

import org.openqa.selenium.*;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import java.time.Duration;
import locators.LoginLocators;

/**
 * LoginPage - Page Object for Salesforce Login/Logout functionality
 * Extends BasePage for common methods
 * 
 * This file is auto-generated by Xenon AI Test Automation Framework
 * Customize as needed for your Salesforce instance
 */
public class LoginPage extends BasePage {
    
    /**
     * Constructor - Initialize with WebDriver
     * @param driver - WebDriver instance
     */
    public LoginPage(WebDriver driver) {
        super(driver);
    }
    
    /**
     * Navigate to the Salesforce login page
     * @param loginUrl - The Salesforce login URL
     */
    public void goToLoginPage(String loginUrl) {
        navigate(loginUrl);
        waitForElement(LoginLocators.USERNAME_INPUT);
    }
    
    /**
     * Perform login with provided credentials
     * @param username - Salesforce username
     * @param password - Salesforce password
     */
    public void login(String username, String password) {
        // Wait for login page to load
        waitForElement(LoginLocators.USERNAME_INPUT);
        
        // Enter credentials
        fill(LoginLocators.USERNAME_INPUT, username);
        fill(LoginLocators.PASSWORD_INPUT, password);
        
        // Click login button
        click(LoginLocators.LOGIN_BUTTON);
        
        // Wait for home page to load (global header indicates successful login)
        waitForHomePage();
    }
    
    /**
     * Complete login flow - navigate to login page and login
     * @param loginUrl - The Salesforce login URL
     * @param username - Salesforce username
     * @param password - Salesforce password
     */
    public void performLogin(String loginUrl, String username, String password) {
        goToLoginPage(loginUrl);
        login(username, password);
    }
    
    /**
     * Wait for home page to fully load after login
     */
    public void waitForHomePage() {
        // Wait for global header to appear (indicates successful login)
        WebDriverWait longWait = new WebDriverWait(driver, Duration.ofSeconds(120));
        longWait.until(ExpectedConditions.visibilityOfElementLocated(LoginLocators.GLOBAL_HEADER));
        
        // Wait for any loading spinners to disappear
        waitForSpinner();
        
        // Additional wait for page stability
        waitForPageLoad();
    }
    
    /**
     * Perform logout from Salesforce
     */
    public void logout() {
        try {
            // Click user profile button to open dropdown
            click(LoginLocators.USER_PROFILE_BUTTON);
            
            // Wait for dropdown menu to appear
            Thread.sleep(1000); // Small delay for animation
            
            // Click logout link
            click(LoginLocators.LOGOUT_LINK);
            
            // Wait for login page to reappear (confirms logout)
            waitForElement(LoginLocators.USERNAME_INPUT, 30);
        } catch (Exception e) {
            System.err.println("Logout failed, attempting direct logout URL: " + e.getMessage());
            // Fallback: Navigate directly to logout URL
            driver.get(driver.getCurrentUrl().split("/lightning")[0] + "/secur/logout.jsp");
        }
    }
    
    /**
     * Check if user is logged in
     * @return boolean
     */
    public boolean isLoggedIn() {
        try {
            return isElementVisible(LoginLocators.GLOBAL_HEADER);
        } catch (Exception e) {
            return false;
        }
    }
    
    /**
     * Check if login page is displayed
     * @return boolean
     */
    public boolean isLoginPageDisplayed() {
        return isElementVisible(LoginLocators.USERNAME_INPUT);
    }
    
    /**
     * Get login error message if displayed
     * @return String - Error message or empty string
     */
    public String getLoginError() {
        try {
            if (isElementVisible(LoginLocators.LOGIN_ERROR)) {
                return getText(LoginLocators.LOGIN_ERROR);
            }
        } catch (Exception e) {
            // No error displayed
        }
        return "";
    }
    
    /**
     * Handle any welcome modals or pop-ups after login
     */
    public void handlePostLoginModals() {
        try {
            // Wait a moment for any modals to appear
            Thread.sleep(2000);
            
            // Check for and close common modals
            if (isElementPresent(LoginLocators.MODAL_CLOSE_BUTTON)) {
                click(LoginLocators.MODAL_CLOSE_BUTTON);
                Thread.sleep(500);
            }
        } catch (Exception e) {
            // No modal to close, continue
        }
    }
    
    /**
     * Navigate to a specific Salesforce Lightning app
     * @param appName - Name of the app to navigate to
     */
    public void navigateToApp(String appName) {
        // Click app launcher
        click(LoginLocators.APP_LAUNCHER);
        
        // Wait for search input and type app name
        waitForElement(LoginLocators.APP_LAUNCHER_SEARCH);
        fill(LoginLocators.APP_LAUNCHER_SEARCH, appName);
        
        // Wait and click on the app result
        try {
            Thread.sleep(1000); // Wait for search results
            By appResult = By.xpath("//mark[text()='" + appName + "']/ancestor::a");
            waitForClickable(appResult).click();
            waitForPageLoad();
        } catch (Exception e) {
            System.err.println("Could not find app: " + appName);
        }
    }
}
