/**
 * BasePage - Abstract base class for all Page Objects
 * Contains common methods used across all pages
 * 
 * This file is auto-generated by Xenon AI Test Automation Framework
 * Customize as needed for your project
 */

import { Page } from '@playwright/test';

export class BasePage {
  protected page: Page;
  protected timeout: number;

  constructor(page: Page) {
    this.page = page;
    this.timeout = 30000; // Default timeout for operations
  }

  /**
   * Navigate to a specific URL
   */
  async navigate(url: string): Promise<void> {
    await this.page.goto(url, { waitUntil: 'networkidle' });
  }

  /**
   * Wait for page to be fully loaded
   */
  async waitForPageLoad(): Promise<void> {
    await this.page.waitForLoadState('networkidle');
  }

  /**
   * Get the current page title
   */
  async getPageTitle(): Promise<string> {
    return await this.page.title();
  }

  /**
   * Get the current page URL
   */
  getCurrentUrl(): string {
    return this.page.url();
  }

  /**
   * Take a screenshot of the current page
   */
  async takeScreenshot(name: string): Promise<void> {
    await this.page.screenshot({ path: `screenshots/${name}.png`, fullPage: true });
  }

  /**
   * Wait for an element to be visible
   */
  async waitForElement(selector: string, timeout: number = this.timeout): Promise<void> {
    await this.page.waitForSelector(selector, { state: 'visible', timeout });
  }

  /**
   * Wait for an element to be hidden
   */
  async waitForElementHidden(selector: string, timeout: number = this.timeout): Promise<void> {
    await this.page.waitForSelector(selector, { state: 'hidden', timeout });
  }

  /**
   * Check if an element exists on the page
   */
  async isElementVisible(selector: string): Promise<boolean> {
    try {
      await this.page.waitForSelector(selector, { state: 'visible', timeout: 5000 });
      return true;
    } catch {
      return false;
    }
  }

  /**
   * Get text content of an element
   */
  async getText(selector: string): Promise<string | null> {
    await this.waitForElement(selector);
    return await this.page.textContent(selector);
  }

  /**
   * Get attribute value of an element
   */
  async getAttribute(selector: string, attribute: string): Promise<string | null> {
    await this.waitForElement(selector);
    return await this.page.getAttribute(selector, attribute);
  }

  /**
   * Scroll element into view
   */
  async scrollIntoView(selector: string): Promise<void> {
    await this.page.locator(selector).scrollIntoViewIfNeeded();
  }

  /**
   * Wait for spinner/loader to disappear (Salesforce specific)
   */
  async waitForSpinner(): Promise<void> {
    try {
      await this.page.waitForSelector('lightning-spinner', { state: 'hidden', timeout: 10000 });
    } catch {
      // Spinner may not be present, continue
    }
  }

  /**
   * Handle any modal dialogs that appear
   */
  handleDialog(action: 'accept' | 'dismiss' = 'accept'): void {
    this.page.on('dialog', async (dialog) => {
      if (action === 'accept') {
        await dialog.accept();
      } else {
        await dialog.dismiss();
      }
    });
  }
}
