/**
 * LoginPage - Page Object for Salesforce Login/Logout functionality
 * Extends BasePage for common methods
 * 
 * This file is auto-generated by Xenon AI Test Automation Framework
 * Customize as needed for your Salesforce instance
 */

import { Page } from '@playwright/test';
import { BasePage } from './BasePage';
import { LoginLocators } from '../locators/LoginLocators';
import { click, fill, waitForElement, getText } from '../utils/CommonActions';

export class LoginPage extends BasePage {
  constructor(page: Page) {
    super(page);
  }

  /**
   * Navigate to the Salesforce login page
   */
  async goToLoginPage(loginUrl: string): Promise<void> {
    await this.navigate(loginUrl);
    await waitForElement(this.page, LoginLocators.usernameInput);
  }

  /**
   * Perform login with provided credentials
   */
  async login(username: string, password: string): Promise<void> {
    // Wait for login page to load
    await waitForElement(this.page, LoginLocators.usernameInput);
    
    // Enter credentials
    await fill(this.page, LoginLocators.usernameInput, username);
    await fill(this.page, LoginLocators.passwordInput, password);
    
    // Click login button
    await click(this.page, LoginLocators.loginButton);
    
    // Wait for home page to load (global header indicates successful login)
    await this.waitForHomePage();
  }

  /**
   * Complete login flow - navigate to login page and login
   */
  async performLogin(loginUrl: string, username: string, password: string): Promise<void> {
    await this.goToLoginPage(loginUrl);
    await this.login(username, password);
  }

  /**
   * Wait for home page to fully load after login
   */
  async waitForHomePage(): Promise<void> {
    // Wait for global header to appear (indicates successful login)
    await waitForElement(this.page, LoginLocators.globalHeader, 60000);
    
    // Wait for any loading spinners to disappear
    await this.waitForSpinner();
    
    // Additional wait for page stability
    await this.page.waitForLoadState('networkidle');
  }

  /**
   * Perform logout from Salesforce
   */
  async logout(): Promise<void> {
    try {
      // Click user profile button to open dropdown
      await click(this.page, LoginLocators.userProfileButton);
      
      // Wait for dropdown menu to appear
      await this.page.waitForTimeout(1000); // Small delay for animation
      
      // Click logout link
      await click(this.page, LoginLocators.logoutLink);
      
      // Wait for login page to reappear (confirms logout)
      await waitForElement(this.page, LoginLocators.usernameInput, 30000);
    } catch (error) {
      console.error('Logout failed, attempting direct logout URL:', (error as Error).message);
      // Fallback: Navigate directly to logout URL
      await this.page.goto('/secur/logout.jsp');
    }
  }

  /**
   * Check if user is logged in
   */
  async isLoggedIn(): Promise<boolean> {
    return await this.isElementVisible(LoginLocators.globalHeader);
  }

  /**
   * Check if login error is displayed
   */
  async hasLoginError(): Promise<boolean> {
    return await this.isElementVisible(LoginLocators.loginError);
  }

  /**
   * Get login error message
   */
  async getLoginErrorMessage(): Promise<string> {
    if (await this.hasLoginError()) {
      return (await getText(this.page, LoginLocators.loginError)) || '';
    }
    return '';
  }

  /**
   * Handle any welcome modals or popups after login
   */
  async dismissWelcomeModals(): Promise<void> {
    try {
      const modalVisible = await this.isElementVisible(LoginLocators.modalContainer);
      if (modalVisible) {
        await click(this.page, LoginLocators.modalCloseButton);
        await this.page.waitForTimeout(500);
      }
    } catch {
      // No modals to dismiss, continue
    }
  }
}
