package config;

/**
 * TestConfig - Configuration class for test environment settings
 * Reads from environment variables or provides defaults
 * 
 * This file is auto-generated by Xenon AI Test Automation Framework
 * Customize default values as needed for your Salesforce instance
 */
public class TestConfig {
    
    // Salesforce Credentials - from environment variables
    public static final String LOGIN_URL = getEnv("SALESFORCE_LOGIN_URL", "https://login.salesforce.com");
    public static final String USERNAME = getEnv("SALESFORCE_USERNAME", "");
    public static final String PASSWORD = getEnv("SALESFORCE_PASSWORD", "");
    
    // Browser Configuration
    public static final String BROWSER = getEnv("BROWSER", "chrome");
    public static final boolean HEADLESS = Boolean.parseBoolean(getEnv("HEADLESS", "false"));
    
    // Timeout Configuration (in seconds)
    public static final int DEFAULT_TIMEOUT = Integer.parseInt(getEnv("DEFAULT_TIMEOUT", "30"));
    public static final int LOGIN_TIMEOUT = Integer.parseInt(getEnv("LOGIN_TIMEOUT", "120"));
    public static final int PAGE_LOAD_TIMEOUT = Integer.parseInt(getEnv("PAGE_LOAD_TIMEOUT", "60"));
    
    // Screenshot Configuration
    public static final String SCREENSHOT_DIR = getEnv("SCREENSHOT_DIR", "screenshots");
    public static final boolean SCREENSHOT_ON_FAILURE = Boolean.parseBoolean(getEnv("SCREENSHOT_ON_FAILURE", "true"));
    
    // Report Configuration
    public static final String REPORT_DIR = getEnv("REPORT_DIR", "test-output");
    
    /**
     * Get environment variable with default fallback
     * @param key - Environment variable name
     * @param defaultValue - Default value if not set
     * @return String - Environment variable value or default
     */
    private static String getEnv(String key, String defaultValue) {
        String value = System.getenv(key);
        if (value == null || value.isEmpty()) {
            value = System.getProperty(key, defaultValue);
        }
        return value;
    }
    
    /**
     * Validate required configuration is present
     * @throws RuntimeException if required config is missing
     */
    public static void validateConfig() {
        if (USERNAME.isEmpty()) {
            throw new RuntimeException("SALESFORCE_USERNAME environment variable is required");
        }
        if (PASSWORD.isEmpty()) {
            throw new RuntimeException("SALESFORCE_PASSWORD environment variable is required");
        }
        if (LOGIN_URL.isEmpty()) {
            throw new RuntimeException("SALESFORCE_LOGIN_URL environment variable is required");
        }
    }
    
    /**
     * Print current configuration (masks password)
     */
    public static void printConfig() {
        System.out.println("=== Test Configuration ===");
        System.out.println("Login URL: " + LOGIN_URL);
        System.out.println("Username: " + USERNAME);
        System.out.println("Password: " + (PASSWORD.isEmpty() ? "(not set)" : "****"));
        System.out.println("Browser: " + BROWSER);
        System.out.println("Headless: " + HEADLESS);
        System.out.println("Default Timeout: " + DEFAULT_TIMEOUT + "s");
        System.out.println("========================");
    }
    
    // Private constructor to prevent instantiation
    private TestConfig() {}
}
