/**
 * TestData - Utilities for managing test data
 * 
 * This file is auto-generated by Xenon AI Test Automation Framework
 */

/**
 * Generate a unique string with timestamp
 */
export function uniqueString(prefix: string = 'Test'): string {
  return `${prefix}_${Date.now()}`;
}

/**
 * Generate a random email address
 */
export function randomEmail(domain: string = 'test.com'): string {
  return `test_${Date.now()}@${domain}`;
}

/**
 * Generate a random phone number
 */
export function randomPhone(): string {
  return `555${Math.floor(1000000 + Math.random() * 9000000)}`;
}

/**
 * Generate a random integer between min and max (inclusive)
 */
export function randomInt(min: number, max: number): number {
  return Math.floor(Math.random() * (max - min + 1)) + min;
}

/**
 * Get current date in specified format
 */
export function getCurrentDate(format: string = 'YYYY-MM-DD'): string {
  const date = new Date();
  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, '0');
  const day = String(date.getDate()).padStart(2, '0');
  
  return format
    .replace('YYYY', String(year))
    .replace('MM', month)
    .replace('DD', day);
}

/**
 * Get future date
 */
export function getFutureDate(daysFromNow: number, format: string = 'YYYY-MM-DD'): string {
  const date = new Date();
  date.setDate(date.getDate() + daysFromNow);
  
  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, '0');
  const day = String(date.getDate()).padStart(2, '0');
  
  return format
    .replace('YYYY', String(year))
    .replace('MM', month)
    .replace('DD', day);
}

/**
 * Pick a random item from an array
 */
export function randomItem<T>(items: T[]): T {
  return items[Math.floor(Math.random() * items.length)];
}
