/**
 * CommonActions - Reusable browser actions for Playwright tests
 * 
 * This file is auto-generated by Xenon AI Test Automation Framework
 * Contains common methods used across all page objects
 */

import { Page } from '@playwright/test';

/**
 * Click on an element with wait
 */
export async function click(page: Page, selector: string, timeout: number = 30000): Promise<void> {
  await page.waitForSelector(selector, { state: 'visible', timeout });
  await page.click(selector);
}

/**
 * Double click on an element
 */
export async function doubleClick(page: Page, selector: string, timeout: number = 30000): Promise<void> {
  await page.waitForSelector(selector, { state: 'visible', timeout });
  await page.dblclick(selector);
}

/**
 * Fill an input field with text
 */
export async function fill(page: Page, selector: string, text: string, timeout: number = 30000): Promise<void> {
  await page.waitForSelector(selector, { state: 'visible', timeout });
  await page.fill(selector, text);
}

/**
 * Clear and fill an input field
 */
export async function clearAndFill(page: Page, selector: string, text: string, timeout: number = 30000): Promise<void> {
  await page.waitForSelector(selector, { state: 'visible', timeout });
  await page.fill(selector, ''); // Clear first
  await page.fill(selector, text);
}

/**
 * Type text into an input field (character by character)
 */
export async function type(page: Page, selector: string, text: string, delay: number = 100): Promise<void> {
  await page.waitForSelector(selector, { state: 'visible' });
  await page.type(selector, text, { delay });
}

/**
 * Wait for an element to be visible
 */
export async function waitForElement(page: Page, selector: string, timeout: number = 30000): Promise<void> {
  await page.waitForSelector(selector, { state: 'visible', timeout });
}

/**
 * Wait for an element to be hidden
 */
export async function waitForElementHidden(page: Page, selector: string, timeout: number = 30000): Promise<void> {
  await page.waitForSelector(selector, { state: 'hidden', timeout });
}

/**
 * Get text content of an element
 */
export async function getText(page: Page, selector: string): Promise<string | null> {
  await page.waitForSelector(selector, { state: 'visible' });
  return await page.textContent(selector);
}

/**
 * Get all text contents of elements matching selector
 */
export async function getAllTexts(page: Page, selector: string): Promise<string[]> {
  await page.waitForSelector(selector);
  return await page.locator(selector).allTextContents();
}

/**
 * Get attribute value of an element
 */
export async function getAttribute(page: Page, selector: string, attribute: string): Promise<string | null> {
  await page.waitForSelector(selector, { state: 'visible' });
  return await page.getAttribute(selector, attribute);
}

/**
 * Check if an element is visible
 */
export async function isVisible(page: Page, selector: string): Promise<boolean> {
  try {
    await page.waitForSelector(selector, { state: 'visible', timeout: 5000 });
    return true;
  } catch {
    return false;
  }
}

/**
 * Check if a checkbox is checked
 */
export async function isChecked(page: Page, selector: string): Promise<boolean> {
  return await page.isChecked(selector);
}

/**
 * Check a checkbox if not already checked
 */
export async function check(page: Page, selector: string): Promise<void> {
  const checked = await page.isChecked(selector);
  if (!checked) {
    await page.check(selector);
  }
}

/**
 * Uncheck a checkbox if checked
 */
export async function uncheck(page: Page, selector: string): Promise<void> {
  const checked = await page.isChecked(selector);
  if (checked) {
    await page.uncheck(selector);
  }
}

/**
 * Select option from dropdown by value
 */
export async function selectByValue(page: Page, selector: string, value: string): Promise<void> {
  await page.waitForSelector(selector, { state: 'visible' });
  await page.selectOption(selector, { value });
}

/**
 * Select option from dropdown by label
 */
export async function selectByLabel(page: Page, selector: string, label: string): Promise<void> {
  await page.waitForSelector(selector, { state: 'visible' });
  await page.selectOption(selector, { label });
}

/**
 * Select option from Salesforce Lightning combobox/picklist
 */
export async function selectComboboxOption(page: Page, comboboxSelector: string, optionText: string): Promise<void> {
  // Click combobox to open dropdown
  await click(page, `${comboboxSelector} button`);
  
  // Wait for dropdown options to appear
  await page.waitForSelector('lightning-base-combobox-item', { state: 'visible' });
  
  // Click the option
  await page.click(`lightning-base-combobox-item:has-text("${optionText}")`);
}

/**
 * Search and select from Salesforce Lightning lookup field
 */
export async function searchAndSelectLookup(page: Page, lookupSelector: string, searchText: string): Promise<void> {
  // Click lookup field to focus
  await click(page, `${lookupSelector} input`);
  
  // Type search text
  await fill(page, `${lookupSelector} input`, searchText);
  
  // Wait for search results
  await page.waitForSelector('lightning-base-combobox-item', { state: 'visible' });
  
  // Click first result
  await page.click('lightning-base-combobox-item:first-child');
}

/**
 * Hover over an element
 */
export async function hover(page: Page, selector: string): Promise<void> {
  await page.waitForSelector(selector, { state: 'visible' });
  await page.hover(selector);
}

/**
 * Scroll element into view
 */
export async function scrollIntoView(page: Page, selector: string): Promise<void> {
  await page.locator(selector).scrollIntoViewIfNeeded();
}

/**
 * Press a key on the keyboard
 */
export async function pressKey(page: Page, key: string): Promise<void> {
  await page.keyboard.press(key);
}

/**
 * Take a screenshot
 */
export async function takeScreenshot(page: Page, name: string): Promise<void> {
  await page.screenshot({ path: `screenshots/${name}.png`, fullPage: true });
}

/**
 * Wait for Salesforce spinner/loader to disappear
 */
export async function waitForSpinner(page: Page): Promise<void> {
  try {
    await page.waitForSelector('lightning-spinner', { state: 'hidden', timeout: 10000 });
  } catch {
    // Spinner may not be present, continue
  }
}

/**
 * Wait for toast message and return its text
 */
export async function getToastMessage(page: Page): Promise<string | null> {
  await page.waitForSelector('div.forceToastMessage, div.toastMessage', { 
    state: 'visible', 
    timeout: 10000 
  });
  return await getText(page, 'div.forceToastMessage, div.toastMessage');
}

/**
 * Wait for specific time
 */
export async function wait(ms: number): Promise<void> {
  return new Promise(resolve => setTimeout(resolve, ms));
}
